### ISSUE TITLE
I also got the wrong message when run elg_demo.py

### ISSUE THREAD

**Issue by 1158755456** [swook/GazeML#42]
(GazeML) D:\labPro\GazeML-master\src>python elg_demo.py --from_video one.mp4
D:\IDE\Anaconda3\envs\GazeML\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\IDE\Anaconda3\envs\GazeML\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\IDE\Anaconda3\envs\GazeML\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\IDE\Anaconda3\envs\GazeML\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\IDE\Anaconda3\envs\GazeML\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\IDE\Anaconda3\envs\GazeML\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "elg_demo.py", line 65, in <module>
    eye_image_shape=(108, 180))
  File "D:\labPro\GazeML-master\src\datasources\video.py", line 22, in __init__
    super().__init__(staging=False, **kwargs)
  File "D:\labPro\GazeML-master\src\datasources\frames.py", line 47, in __init__
    shuffle=False, staging=staging, **kwargs)
  File "D:\labPro\GazeML-master\src\core\data_source.py", line 59, in __init__
    labels, dtypes, shapes = self._determine_dtypes_and_shapes()
  File "D:\labPro\GazeML-master\src\core\data_source.py", line 194, in _determine_dtypes_and_shapes
    raw_entry = next(self.entry_generator(yield_just_one=True))
  File "D:\labPro\GazeML-master\src\datasources\frames.py", line 106, in entry_generator
    self.detect_landmarks(frame)
  File "D:\labPro\GazeML-master\src\datasources\frames.py", line 171, in detect_landmarks
    predictor = get_landmarks_predictor()
  File "D:\labPro\GazeML-master\src\datasources\frames.py", line 371, in get_landmarks_predictor
    _landmarks_predictor = dlib.shape_predictor(dat_path)
RuntimeError: Error deserializing object of type int64
   while deserializing a floating point number.
   while deserializing a dlib::matrix
   while deserializing object of type std::vector
   while deserializing object of type std::vector
   while deserializing object of type std::vector

**Comment by 5488287** [comment]
Hi, do you have solved this problem? I meet this either and can not deal it. I will feel very appreciated if you can help me.

**Comment by zeronatdo** [comment]
You can try download file "shape_predictor_5_face_landmarks.dat" then put it to "src/3rdparty/"

**Comment by 1158755456** [comment]
> You can try download file "shape_predictor_5_face_landmarks.dat" on http://dlib.net/files/ then put it to "src/3rdparty/"

Thank! But your solution doesn't work

**Comment by 1158755456** [comment]
> Hi, do you have solved this problem? I meet this either and can not deal it. I will feel very appreciated if you can help me.

Sorry I didn't solve the problem.

**Comment by DaddyWesker** [comment]
zeronatdo's solutions helped. You just need to download shape_predictor_5_face_landmarks.dat.bz2 from the link he provided, place it in src/3rdparty and unzip. And don;t forget to check the name of the .dat file
