### ISSUE TITLE
TypeError: profile() missing 1 required positional argument: 'graph'

### ISSUE THREAD

**Issue by kaisark** [swook/GazeML#51]
I ran into a runtime error with TF 1.5 (see below). 

Which version of tensorflow did you test with?

------------
(cv40py35) nvidia@tegra-ubuntu:~/cviz/GazeML/src$ python3 elg_demo.py
2019-12-03 17:27:32.703689: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:859] ARM64 does not support NUMA - returning NUMA node zero
2019-12-03 17:27:32.703844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: NVIDIA Tegra X1 major: 5 minor: 3 memoryClockRate(GHz): 0.9984
pciBusID: 0000:00:00.0
totalMemory: 3.89GiB freeMemory: 1.84GiB
2019-12-03 17:27:32.703909: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)

(process:15956): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
VIDEOIO ERROR: V4L: Property <unknown property string>(6) not supported by device
03/12 17:27 INFO Initialized data source: "Webcam"
03/12 17:28 INFO Built model.
Traceback (most recent call last):
  File "elg_demo.py", line 92, in <module>
    'loss_terms_to_optimize': {'dummy': ['hourglass', 'radius']},
  File "/home/nvidia/cviz/GazeML/src/models/elg.py", line 27, in __init__
    super().__init__(tensorflow_session, **kwargs)
  File "/home/nvidia/cviz/GazeML/src/core/model.py", line 101, in __init__
    self._build_all_models()
  File "/home/nvidia/cviz/GazeML/src/core/model.py", line 190, in _build_all_models
    tf.profiler.ProfileOptionBuilder.float_operation()
TypeError: profile() missing 1 required positional argument: 'graph'
Exception ignored in: <bound method BaseModel.__del__ of <models.elg.ELG object at 0x7f5899b710>>
Traceback (most recent call last):
  File "/home/nvidia/cviz/GazeML/src/core/model.py", line 109, in __del__
  File "/home/nvidia/cviz/GazeML/src/core/data_source.py", line 156, in cleanup
  File "/home/nvidia/.virtualenvs/cv40py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
  File "/home/nvidia/.virtualenvs/cv40py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1128, in _run
  File "/home/nvidia/.virtualenvs/cv40py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
  File "/home/nvidia/.virtualenvs/cv40py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
  File "/home/nvidia/.virtualenvs/cv40py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1320, in _run_fn
  File "/home/nvidia/.virtualenvs/cv40py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1381, in _extend_graph
  File "/home/nvidia/.virtualenvs/cv40py35/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1042, in SerializeToString
  File "/home/nvidia/.virtualenvs/cv40py35/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1051, in SerializePartialToString
  File "/home/nvidia/.virtualenvs/cv40py35/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1063, in InternalSerialize
  File "/home/nvidia/.virtualenvs/cv40py35/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 147, in GetOptions
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable

**Comment by kaisark** [comment]
I installed a newer version of tensorflow...
