### ISSUE TITLE
Training dpg

### ISSUE THREAD

**Issue by nhathoang0110** [swook/GazeML#70]
It is my error. I am training on gpu.Please help me

2020-07-30 08:58:38.623964: E tensorflow/core/common_runtime/executor.cc:642] Executor failed to create kernel. Invalid argument: Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node hourglass/hg_1/depth1/pool/MaxPool}}]]
2020-07-30 08:58:39.018768: W tensorflow/core/kernels/queue_base.cc:285] _0_HDFdatasetsMPIIGazeh5/random_shuffle_queue: Skipping cancelled dequeue attempt with queue not closed
Traceback (most recent call last):
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node hourglass/hg_1/depth1/pool/MaxPool}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dpg_train.py", line 96, in <module>
    num_epochs=20,
  File "/home/hoangnn/pose/GazeML/src/core/model.py", line 327, in train
    self.use_batch_statistics: True,
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
         [[node hourglass/hg_1/depth1/pool/MaxPool (defined at /home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'hourglass/hg_1/depth1/pool/MaxPool':
  File "dpg_train.py", line 89, in <module>
    testing=True,
  File "/home/hoangnn/pose/GazeML/src/models/dpg.py", line 26, in __init__
    super().__init__(tensorflow_session, **kwargs)
  File "/home/hoangnn/pose/GazeML/src/core/model.py", line 101, in __init__
    self._build_all_models()
  File "/home/hoangnn/pose/GazeML/src/core/model.py", line 184, in _build_all_models
    _build_train_or_test(mode='train')
  File "/home/hoangnn/pose/GazeML/src/core/model.py", line 167, in _build_train_or_test
    output_tensors, loss_terms, metrics = self.build_model(data_sources, mode=mode)
  File "/home/hoangnn/pose/GazeML/src/models/dpg.py", line 128, in build_model
    x = self._build_hourglass(x, steps_to_go=4, num_features=self._hg_num_feature_maps)
  File "/home/hoangnn/pose/GazeML/src/models/dpg.py", line 259, in _build_hourglass
    low1 = self._apply_pool(x, kernel_size=2, stride=2)
  File "/home/hoangnn/pose/GazeML/src/models/dpg.py", line 215, in _apply_pool
    name='pool',
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/layers/pooling.py", line 311, in max_pooling2d
    return layer.apply(inputs)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1700, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/layers/base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 854, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 234, in wrapper
    return converted_call(f, options, args, kwargs)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 439, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 330, in _call_unconverted
    return f(*args, **kwargs)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/pooling.py", line 248, in call
    data_format=conv_utils.convert_data_format(self.data_format, 4))
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 3815, in max_pool
    name=name)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 5674, in max_pool
    data_format=data_format, name=name)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/hoangnn/.conda/envs/nh/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

terminate called without an active exception
Aborted (core dumped)

**Comment by xgbm** [comment]
Change “NCHW”to “NHWC”
